/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type UserTransformer from '#transformers/user_transformer'
import type AssigneeTransformer from '#transformers/assignee_transformer'
import type TaskTransformer from '#transformers/task_transformer'

export namespace Data {
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Assignee = InferData<AssigneeTransformer>
  export namespace Assignee {
    export type Variants = InferVariants<AssigneeTransformer>
  }
  export type Task = InferData<TaskTransformer>
  export namespace Task {
    export type Variants = InferVariants<TaskTransformer>
  }
}
